services:
  - type: web
    name: nulleinstech-api
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
